baseurl: "/"
languageCode: "en-us"
title: "Stefan Tilkov"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "Stefan Tilkov"
  footer: "&copy; [Stefan Tilkov](https://tilkov.com) 2020 | [Twitter](https://twitter.com/stilkov)"

markup:
  goldmark:
    renderer:
      unsafe: true
